[package]
name = "rust_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mustache = "0.9.0"
serde = "1.0.150"
serde_derive = "1.0.150"
serde_qs = "0.10.1"
